add: ovirt 4.4 repos
oVirt/ovirt-ansible-repositories pull request #48
Opened 2020-07-13 14:42 UTC by mnecas

@mwperina @dangel101

2020-07-13 14:47 UTC, mwperina requested changes
4.4 GA files looks good to me,  but shouldn't we also remove 4.4 beta configuration? This will be part of RHV 4.4 GA, so it doesn't make any sense to install beta when GA is released

2020-07-13 20:41 UTC, mwperina requested changes
It looks good to me, just please switch the default to 4.4

2020-07-13 20:41 UTC, mwperina commented on README.md
> +| ovirt_repositories_ovirt_version           | 4.3                   | oVirt release version (Supported versions [4.1, 4.2, 4.3, 4.4]). Will be used to enable the required repositories in case <i>ovi
Please change the default to 4.4

2020-07-13 20:41 UTC, mwperina commented
@dangel101

2020-07-14 08:30 UTC, sandrobonazzola approved these changes
Looks good to me

2020-07-14 08:30 UTC, merged